{
 "title": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 v4",
 "description": "Grafana Dashboard for Veeam Backup for Microsoft Office 365 Dashboard - Works only with v4.0 of VBO",
 "tags": [
  "Veeam",
  "Office 365"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "organization",
    "label": "Organization",
    "query": "SHOW TAG VALUES FROM veeam_office365_organization WITH KEY=veeamOrgName"
   },
   {
    "name": "job",
    "label": "Backup Job",
    "query": "SHOW TAG VALUES FROM veeam_office365_jobs WITH KEY=veeamjobname"
   },
   {
    "name": "proxies",
    "label": "Backup Proxies",
    "query": "SHOW TAG VALUES FROM veeam_office365_proxies WITH KEY=proxies"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "SHOW TAG VALUES FROM veeam_office365_repository WITH KEY=repository"
   },
   {
    "name": "objectstorage",
    "label": "Object Storage",
    "query": "SHOW TAG VALUES FROM veeam_office365_objectstorage WITH KEY=objectname"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "content": "<img src=\"https://www.jayp.io/wp-content/uploads/2020/05/Veeam_logo_topaz_2019.png\">",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Licensed Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "licensedUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "New Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_organization",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "newUsers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamOrgName", "operator": "=~", "value": "/^$organization$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads Numbers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_proxies",
     "query": "SELECT sum(\"threadsNumber\") FROM \"veeam_office365_proxies\" WHERE (\"proxies\" =~ /^$proxies$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "threadsNumber" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "proxies", "operator": "=~", "value": "/^$proxies$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Objects Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "processedObjects" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Change Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_repository",
     "select": [
      [
       { "params": [ "freeSpace" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "repository", "operator": "=~", "value": "/^$repository$/" }
     ]
    }
   ]
  },
  { "title": "Summaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "$job - Last Result",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsProcessed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "$job - Restore - Items Recovered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_restoresession",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "itemsSuccess" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Job Read/Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Read MB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "readRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "writeRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Processing Rate/Transferred Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "KBs", "label": "Processed KB/s" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname - processed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "processingRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    },
    {
     "alias": "$tag_veeamjobname - transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "transferredData" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Duration in Seconds" }
   ],
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE \"esxhostname\" = ($esxi) AND $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "totalDuration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "$tag_veeamjobname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "veeamjobname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_office365_jobs",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "veeamjobname", "operator": "=~", "value": "/^$job$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "graph",
   "description": "This Panel includes the Backup Repositories.\nWhen using Object Storage, it will appear on the right column with the prefix called OBJECT.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "decbytes", "label": "Used Space GB" }
   ],
   "targets": [
    {
     "alias": "CACHE - $tag_repository",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "SELECT  (mean(\"capacity\") - mean(\"freeSpace\"))  FROM  \"veeam_office365_repository\" WHERE (\"repository\" =~ /^$repository$/) AND $timeFilter GROUP BY time(5m), \"repository\"",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    },
    {
     "alias": "OBJECT - $tag_objectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"usedSpaceGB\") FROM \"veeam_office365_objectstorage\" WHERE (\"objectname\" =~ /^$objectstorage$/) AND $timeFilter GROUP BY time($__interval), \"objectname\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}