{
 "title": "Veeam",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Successful Backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "successfulbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "Backup Read",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "totalbackupread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "Failed Backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "failedbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "Warning Backups",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "warningbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "Repo Free Space",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "REPO_JP-NAS-002_Backup" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "content": "<img src=\"https://www.jayp.io/wp-content/uploads/2020/05/Veeam_logo_topaz_2019.png\">"
  },
  {
   "title": "VEEAMSRV-CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       { "params": [ "user_time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       { "params": [ "processor_time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "VEEAMSRV-RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       { "params": [ "available_bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Nonpaged_Bytes" ], "type": "field" },
       { "params": [ "nonpaged_bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "Pool_Paged_Bytes" ], "type": "field" },
       { "params": [ "paged_bytes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "VEEAMSRV-NETWORK",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "measurement": "win_net",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       { "params": [ "bytes_received" ], "type": "alias" }
      ],
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       { "params": [ "bytes_sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "Network Interface" },
      {
       "condition": "AND",
       "key": "instance",
       "operator": "=",
       "value": "Intel[R] PRO_1000 MT Network Connection"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Read/Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "totalbackupread" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "backup read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  },
  {
   "title": "Free Space per Repository",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeamstats",
     "select": [
      [
       { "params": [ "REPO_JP-NAS-002_Backup" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Veeam_Repo" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "HOST" }
     ]
    }
   ]
  }
 ]
}